// @generated by scripts/design-build.js from design/tokens.yaml — do not edit.
// Skin: aurora (Indigo-slate, layered, luminous). The menu bar follows the system appearance,
// so every role is a dark/light pair resolved at draw time.
import SwiftUI
import AppKit

enum DesignTokens {
    static let version = 1

    struct Dyn {
        let dark: String
        let light: String
        /// Follows the current appearance, including live switching.
        var color: Color {
            Color(nsColor: NSColor(name: nil) { appearance in
                appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
                    ? NSColor(dkHex: self.dark) : NSColor(dkHex: self.light)
            })
        }
        func resolved(_ scheme: ColorScheme) -> Color {
            Color(nsColor: NSColor(dkHex: scheme == .dark ? dark : light))
        }
    }

    // surfaces and ink
    static let plane = Dyn(dark: "#0a0d14", light: "#f5f7fc")
    static let surface1 = Dyn(dark: "#111624", light: "#ffffff")
    static let surface2 = Dyn(dark: "#171d2e", light: "#f1f4fa")
    static let surface3 = Dyn(dark: "#1f2637", light: "#e6eaf4")
    static let textPrimary = Dyn(dark: "#f3f6fc", light: "#0d1220")
    static let textSecondary = Dyn(dark: "#a7b2c9", light: "#4b5468")
    static let textMuted = Dyn(dark: "#7d879e", light: "#6c7488")
    static let grid = Dyn(dark: "#1e2436", light: "#e4e8f1")
    static let axis = Dyn(dark: "#2b3348", light: "#c7cddb")
    static let accent = Dyn(dark: "#8f9dff", light: "#3d4dd6")
    static let accentSolid = Dyn(dark: "#4a5ae0", light: "#3d4dd6")
    static let accentInk = Dyn(dark: "#ffffff", light: "#ffffff")

    // status — reserved for state, never a series, never a mark
    static let good = Color(nsColor: NSColor(dkHex: "#0ca30c"))
    static let warning = Color(nsColor: NSColor(dkHex: "#fab219"))
    static let serious = Color(nsColor: NSColor(dkHex: "#ec835a"))
    static let critical = Color(nsColor: NSColor(dkHex: "#d03b3b"))

    // categorical series, fixed order, assigned by entity
    static let seriesDark: [String] = ["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9", "#e66767"]
    static let seriesLight: [String] = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
    static func series(_ index: Int, _ scheme: ColorScheme) -> Color {
        let steps = scheme == .dark ? seriesDark : seriesLight
        return Color(nsColor: NSColor(dkHex: steps[index % steps.count]))
    }
    /// Appearance-following series step, for views that do not read a ColorScheme.
    static func series(_ index: Int) -> Color {
        Dyn(dark: seriesDark[index % seriesDark.count], light: seriesLight[index % seriesLight.count]).color
    }

    /// Raw status hexes for AppKit call sites (the status item title) that need an NSColor.
    enum StatusHex {
        static let good = "#0ca30c"
        static let warning = "#fab219"
        static let serious = "#ec835a"
        static let critical = "#d03b3b"
    }
    static let sequentialDark: [String] = ["#184f95", "#1c5cab", "#256abf", "#2a78d6", "#3987e5", "#5598e7", "#86b6ef"]
    static let sequentialLight: [String] = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#2a78d6", "#1c5cab", "#104281"]

    // shape and space
    static let radius: CGFloat = 14
    static let radiusSm: CGFloat = 9
    static let space: [CGFloat] = [2, 4, 6, 8, 10, 12, 14, 16, 20, 24, 32, 40, 56, 72]

    // motion · ui tier (seconds)
    static let durPress: Double = 0.120
    static let durFast: Double = 0.160
    static let durBase: Double = 0.220
    static let durSlow: Double = 0.300

    // type scale (points)
    static let fsMicro: CGFloat = 10.5
    static let fsLabel: CGFloat = 11.5
    static let fsCaption: CGFloat = 12.5
    static let fsBody: CGFloat = 13.5
    static let fsTitle: CGFloat = 15
    static let fsFigure: CGFloat = 25
    static let fsHero: CGFloat = 42
    static let fsDisplay: CGFloat = 60
}

extension NSColor {
    /// "#rrggbb" → NSColor in sRGB. A malformed token is a build error upstream, so this never guesses.
    convenience init(dkHex: String) {
        var s = dkHex.trimmingCharacters(in: .whitespaces)
        if s.hasPrefix("#") { s.removeFirst() }
        let v = UInt32(s, radix: 16) ?? 0
        self.init(srgbRed: CGFloat((v >> 16) & 0xff) / 255,
                  green: CGFloat((v >> 8) & 0xff) / 255,
                  blue: CGFloat(v & 0xff) / 255,
                  alpha: 1)
    }
}
